### ISSUE TITLE
《bug 制造者》

### ISSUE THREAD

**Issue by taozhiyu** [Littlefean/jsGame2048#1]
[![image](https://pic.rmb.bdstatic.com/bjh/8fd693722987c44212dd2265fdc6fe09.png "报错截图")](https://pic.rmb.bdstatic.com/bjh/8fd693722987c44212dd2265fdc6fe09.png)

咳咳，本来想提pr来着，bug有点多。。。不大想动了

不是列表而是代办，是方便你修复打卡（不是:joy: ） 

### 已知bug

- [ ] 刚生成棋盘时，应该调用一次随机生成
- [ ] 增加自动的速度设置，暂停、恢复按钮
- [ ] （全部键盘事件都屏蔽了。。。出bug了`F5`刷新都按不了。。。）
- [ ] undefined配置无效
- [ ] （如下图）四个方向点击移动监听（可以用空白div）

    > [![监听](https://pic.rmb.bdstatic.com/bjh/b6886576efa06ffeb3b4e9c6b221fdfe.png "监听")](https://pic.rmb.bdstatic.com/bjh/b6886576efa06ffeb3b4e9c6b221fdfe.png)

### 特性？

- 为什么null那几个概率最大值会是100。。。

    > ↓↓这是彩蛋吗？↓↓
    >
    > [![NULL](https://pic.rmb.bdstatic.com/bjh/e506dccf3d8403296a3537b49268819f.png "操作不了的特性")](https://pic.rmb.bdstatic.com/bjh/e506dccf3d8403296a3537b49268819f.png)

- 每次生成的都是1

  > 也就是说如果每次都按住一个方向，就可以获得一张……
  >
  > [![概率论](https://pic.rmb.bdstatic.com/bjh/85304d2a87895353853b5ef4a08808b3.png "概率分布图")](https://pic.rmb.bdstatic.com/bjh/85304d2a87895353853b5ef4a08808b3.png)
  >
  > 概率分布图？
  > 
  > [![BUG?!](https://pic.rmb.bdstatic.com/bjh/c94106194d28fc66b6c0a34a235e7bc4.png "新bug")](https://pic.rmb.bdstatic.com/bjh/c94106194d28fc66b6c0a34a235e7bc4.png)
  >
  > 似乎又有新bug了，中间下面的三个1，按`上`没有合并

### 建议

- [ ] `无限`那个div，family修改为：sans-serif，兼容性更强更美观
- [ ] 监听事件抽取出来，放到最外面，使用参数去控制是否监听和监听对应的方向
- [ ] 移动动画
- [ ] 每次更新的时候，所有的div都要重绘，可以尝试使用canvas（脏区重绘）或者刷新的时候比较和上一次div的区别
- [ ] 添加readme
- [ ] 添加issue模板
- [ ] （bilibili评论里我也说了）试一下`TS`重构，可以~~提高效率~~(踩更多坑)

不知道有生之年[在gitee提交的issue](https://gitee.com/littlefean/js-game2048/issues/I57145)还能不能通过审核了=\_=

最后建议通过clone同步库，然后选择一遍进行维护

**Comment by taozhiyu** [comment]
为了防止不知名的因素导致图片国内无法正常加载，使用的百度的图床
虽然github会转发图片，如果看不到可以f12选择元素后看data-canonical-src属性获得原图片链接
（图片外面加了a链接，点击应该就行:)）

**Comment by Littlefean** [comment]
收到！感谢细致的issuee，我在github里面看到你发的所有的图啦，
说来有点惭愧，自己写了很多的bug都没有好好修理。

不过还是非常感谢，最近有一点忙碌，有时间我会更新的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Littlefean/jsGame2048"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 中午12:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Littlefean/jsGame2048] 《bug 制造者》 (Issue #1)





 
（为了防止不知名的因素导致图片国内无法正常加载，使用的百度的图床）

**Comment by taozhiyu** [comment]
（gitee这波我属实是提前预判了）
一直就觉得用的不是很顺手，手机上强行把设置按钮扣了，
回复还一直屏蔽，属实是反开源行为
